144, Искандяров, 1.1
rinatisk/spbu_2020_c_homeworks-1 pull request #1
Opened 2020-09-21 14:05 UTC by rinatisk

2020-09-22 15:18 UTC, SpirinEgor requested changes
Файл с решением лучше положить в отдельную папку, например, homeworks_1. А то в дальнейшем будет груда файлов, которую сложно разобрать

2020-09-22 15:18 UTC, SpirinEgor commented on 1sol.c
> +    int mtrx[n][n];
Напиши matrix, не сильно много места занимает)

2020-09-22 15:18 UTC, SpirinEgor commented on 1sol.c
> +    int n;
А тут забыл инициализировать?

2020-09-22 15:18 UTC, SpirinEgor commented on 1sol.c
> +    y = n / 2;
Эти переменные прям тут можно объявить и задать им сразу нужное значение

2020-09-22 15:18 UTC, SpirinEgor commented on 1sol.c
> +    int mtrx[n][n];
И память под этот массив в конце надо освободить.

2020-09-24 14:07 UTC, SpirinEgor requested changes

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +    scanf("%d", &n);
Текст приглашения бы

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +            scanf("%d", &matrix[i][j]);
И тут тоже

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +                switch (d) {
Чет по имени переменной не ясно, что это за `d` такое

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +        for (int j = 0; j < (k == (n - 1) ? 3 : 2); j++) {
Жесть тут условие цикла, вынести бы в отдельную переменную

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +    for (int k = 1; k <= (n - 1); k++) {
Кажется, что строгое неравенство до `n` более привычная запись

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +                printf("%d%s", matrix[x][y], " ");
Пробел можно было прям при указании формата строки поставить, без отдельного аргумента.

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +    int matrix[n][n];
При больших `n` это не будет работать

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +    free(matrix);
В чате было про то, что этого не нужно делать со статическим массивом.

2020-09-24 14:07 UTC, SpirinEgor commented on Homeworks_1/1sol.c
> +}
Ну тут уже сам гитхаб ругается, что нет новой линии в конце файла

2020-09-25 12:12 UTC, SpirinEgor requested changes
Что-то пошло не так при слияние. Почему-то удалились 2 и 3 задача, которые уже в мастере

2020-09-25 12:12 UTC, SpirinEgor commented on library/commonUtils/numericOperations.h
> +void dynamic_array_free(int** A, int N);
Я бы предложил это вынести в arrayOperations. Кажется более логичным

2020-09-25 12:12 UTC, SpirinEgor commented on library/commonUtils/numericOperations.c
> +    int** A = (int**)malloc(N * sizeof(int*));
Лучше использовать calloc, так как он ещё и инициализирует эту память нулями

2020-09-25 12:12 UTC, SpirinEgor commented on CMakeLists.txt
> -target_link_libraries(2sol library)
Почему ты удаляешь таргеты для 2 и 3 задания. Они уже лежат в мастере, поэтому не должны трогаться

2020-09-30 18:19 UTC, rinatisk commented
@SpirinEgor

2020-09-30 19:16 UTC, SpirinEgor approved these changes

2020-09-30 19:16 UTC, merged