144. Искандяров, 2.2
rinatisk/spbu_2020_c_homeworks-1 pull request #10
Opened 2020-09-30 08:00 UTC by rinatisk

2020-10-01 06:28 UTC, rinatisk commented
@nbirillo

2020-10-05 12:51 UTC, nbirillo requested changes

2020-10-05 12:51 UTC, nbirillo commented on Homeworks_2/2_2sol.c
> +int main()
Утечки памяти
![image](https://user-images.githubusercontent.com/8993915/95081330-0fc84e00-0722-11eb-9905-bfe7892f5ebe.png)
А еще функция int, но она ничего не возвращает

2020-10-05 12:51 UTC, nbirillo commented on Homeworks_2/2_2sol.c
> +const int tryLength = 4;
Пусть длину загадываемого числа вводит пользователь - например от 4 до 10. Нижнюю границу выбирай сам, верхняя определяется количеством уникальных цифр

2020-10-05 12:51 UTC, nbirillo commented on Homeworks_2/2_2sol.c
> +    }
Цифры должны быть уникальные

2020-10-05 12:51 UTC, nbirillo commented on Homeworks_2/2_2sol.c
> +    printf("Write you numbers throw a space\n");
Ну вообще не очень удобно вводить число через пробел, сделай, чтобы можно было вводить просто число

2020-10-05 12:51 UTC, nbirillo commented on Homeworks_2/2_2sol.c
> +        computerGuess[i] = rand() % 6;
А еще у тебя каждый запуск будет генерироваться одинаковое число

2020-10-09 11:13 UTC, nbirillo requested changes

2020-10-09 11:13 UTC, nbirillo commented on Homeworks_2/2_2sol.c
> +int main()
Кажется, что-то тут не так (вывела загаданные цифры, чтоб проверять было удобнее)
![image](https://user-images.githubusercontent.com/8993915/95576543-4dd2b400-0a39-11eb-865d-71511716c7cd.png)

2020-10-09 11:13 UTC, nbirillo commented on Homeworks_2/2_2sol.c
> +int main()
В остальном все ок

2020-10-09 17:17 UTC, rinatisk commented on Homeworks_2/2_2sol.c
> +int main()
@nbirillo вверх ногами записывал попытку, исправил

2020-10-12 07:18 UTC, nbirillo approved these changes
Зачтено!

2020-10-12 07:18 UTC, merged