144, Искандяров, 3.1
rinatisk/spbu_2020_c_homeworks-1 pull request #11
Opened 2020-10-06 07:43 UTC by rinatisk

2020-10-09 19:16 UTC, SokolovYaroslav requested changes
`#include <malloc.h>`
У меня не билдится.

А ещё у меня valgrind ругается.

2020-10-09 19:16 UTC, SokolovYaroslav commented on CMakeLists.txt
>          )
Странный отступ.

2020-10-09 19:16 UTC, SokolovYaroslav commented on CMakeLists.txt
> +target_link_libraries(sol3_1 library)
Файлы без пустых строк в конце -- зло

2020-10-09 19:16 UTC, SokolovYaroslav commented on Homeworks_3/3_1sol.c
> +}
Жесть стена текста. Обычно код бьют на смысловые блоки пустыми строками.

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +#endif //UNTITLED_LIST_H
Не вижу `tail` и `head`

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    ListElement* temp = list->head;
`temp` -- плохое название переменной. Можно придумать что-нибудь получше, например `to_print`

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    list->tail->next = NULL;
Бессмысленно, но ладно

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        free(current);
В идеале бы не вызывать `free` напрямую. А сделать отдельную функцию для этого

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    ListElement* elem = list->head;
С отрицательной позицией сработает? А с позицией 100500?

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (list->size < position) {
yoda conditions -- нехорошо

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        return true;
А почему `true`?

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        return false;
А тут почему `false`?
Наоборот должно быть.

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        ListElement* current = retrieve(position, list);
О, ну хоть кто-то догадался использовать уже имеющиеся функции

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (list->size < position) {
Снова замечание про отрицательный индекс.

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    int position = 1;
То есть тут 1-индексация? Это не интутивно и вообще зло.

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +int locate(ListElement* value, List* list)
Почему ты называешь `ListElement*` как `value`? Это сбивает с толку. У тебя ведь в структуре написано, что `value` -- это число внутри элемента.

2020-10-09 19:16 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        return false;
Ко всему остальному также это относится.

2020-10-10 06:04 UTC, rinatisk commented on library/commonUtils/list.h
> +#endif //UNTITLED_LIST_H
![image](https://user-images.githubusercontent.com/70975579/95647364-7b6e3a80-0ad7-11eb-9616-fdb0880179c5.png)

2020-10-10 06:04 UTC, rinatisk commented on library/commonUtils/list.c
> +int locate(ListElement* value, List* list)
![image](https://user-images.githubusercontent.com/70975579/95647387-a6588e80-0ad7-11eb-868a-9bd3bb3901a3.png)

2020-10-10 10:18 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +int locate(ListElement* value, List* list)
Забавно.
Ну ладно, раз так заказчик просит...

2020-10-10 10:19 UTC, SokolovYaroslav commented on library/commonUtils/list.h
> +#endif //UNTITLED_LIST_H
Ну да. Вроде написано, что такое должно быть, а у тебя не вижу.

2020-10-10 10:20 UTC, SokolovYaroslav commented
Да кстати. У меня твой проект не запускается из-за `#include <malloc.h>` в `numericOperations.c`. Надо поправить

2020-10-11 14:07 UTC, SokolovYaroslav requested changes

2020-10-11 14:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +int locate(ListElement* value, List* list)
Функция не работает, если передать туда элемент, которого там нет. Хотелось бы, чтобы она отдавала -1 в таком случае

2020-10-11 14:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +bool delete (int position, List* list)
А если отрицательная позиция пришла?

2020-10-11 14:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > list->size || position < 0) {
В `insert` и `retrieve` вроде почти одинаковые ифы, а записаны ну очень по-разному. Давай по-единообразнее

2020-10-11 14:07 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        temp = current;
имена а-ля `tmp`, `temp`, `temporary` не очень информативные. Можно придумать чт-нибудь получше. Например здесь `toDelete`.

2020-10-11 14:23 UTC, SokolovYaroslav commented
Ты уверен?)
Я сходу вижу багу

2020-10-11 14:27 UTC, SokolovYaroslav requested changes

2020-10-11 14:27 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position < list->size && position > -1) {
Было правильно, теперь нет

2020-10-11 14:27 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position < list->size && position > -1) {
Про однообразность ифов актуально еще

2020-10-11 14:31 UTC, rinatisk commented on library/commonUtils/list.c
> +    if (position < list->size && position > -1) {
я понял, что там развернуть забыл, а про однообразие не понимаю, если я сделаю, например, чтобы в обоих условиях был только знак больше или только знак меньше, то будет слева от знака стоять -1 или 0, так же тоже некрасиво

2020-10-11 14:34 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position < list->size && position > -1) {
Не, я про то, что в одном месте > -1, а в другом >= 0. А еще в одном месте ты проверяешь отрицание и сразу возвращаешь false, а в другом в теле ифа вся логика, и только в онце возвращение чего-то при плохих аргументах

2020-10-11 14:39 UTC, rinatisk commented on library/commonUtils/list.c
> +    if (position < list->size && position > -1) {
логику исправлю, а >= 0 у меня вроде нигде и нет, там оба строгие

2020-10-11 14:50 UTC, SokolovYaroslav requested changes

2020-10-11 14:50 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +        return true;
Так. ну я явно не проговорил, думая, что вам это уже проговаривали)
Я имел в виду, что надо сделать, чтобы сначала при плохих услових мы возвращались, а потом шло основное тело функции. Тогда ты сможешь избежать одного уровня вложенности.
Типа сначала сразу отсекаем плохие входные данные, а потом работаем, будто они хорошие

2020-10-11 15:30 UTC, SokolovYaroslav requested changes

2020-10-11 15:30 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > list->size || position < 0) {
То есть `list->size` норм возвращать?

2020-10-11 15:30 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +bool delete (int position, List* list)
Пробел откуда-то

2020-10-11 15:30 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > list->size || position < 0) {
Удалять элемент `list->size` норм?

2020-10-11 17:16 UTC, rinatisk commented on library/commonUtils/list.c
> +bool delete (int position, List* list)
@SokolovYaroslav когда функция называлась delete, гитхаб не пускал коммит без пробела, я переназвал сейчас и вроде пропустил. Пруф - 
![image](https://user-images.githubusercontent.com/70975579/95685118-98515d80-0bfe-11eb-96aa-b983658a9dcb.png)

2020-10-12 08:06 UTC, SokolovYaroslav requested changes
Чел)))
Хоть бы чуть чуть посмотрел, что ты там наисправлял

2020-10-12 08:06 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > list->size || position < 0) {
Если что, то тут до сих пор баг :)

2020-10-12 08:06 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    if (position > list->size - 1 || position < 0) {
А как вставлять на последнее место?

2020-10-17 18:20 UTC, SokolovYaroslav requested changes
Валгринд ругается

2020-10-17 18:20 UTC, SokolovYaroslav commented on library/commonUtils/list.c
> +    ListElement* temp = list->tail;
Снова темпы...

2020-10-18 10:54 UTC, rinatisk commented
> Валгринд ругается

можно мне скриншот, пожалуйста

2020-10-18 13:32 UTC, SokolovYaroslav commented
> > Валгринд ругается
> 
> можно мне скриншот, пожалуйста, чтобы я знал что исправлять

Хм, а у тебя он не ругается?

2020-10-18 13:34 UTC, SokolovYaroslav commented
Щас у меня тоже перестал

2020-10-18 13:36 UTC, merged

2020-10-18 13:38 UTC, SokolovYaroslav commented
Ставлю 1.3, так как позже дедлайна + после 4-го ревью в коде был баг

2020-10-18 14:23 UTC, rinatisk commented
![image](https://user-images.githubusercontent.com/70975579/96370455-8d4e7e00-1166-11eb-8bcf-503a60687cbd.png)