144, Искандяров, 3.2
rinatisk/spbu_2020_c_homeworks-1 pull request #12
Opened 2020-10-08 09:52 UTC by rinatisk

2020-10-09 20:56 UTC, SokolovYaroslav requested changes
В задании написано, что нужно переиспользовать лист из прошлого задания.
А еще необходимо вывести одно число в качестве ответа.
А еще на тесте n=5 m=3 пишет, что ты что-то освобождаешь два раза.

2020-10-17 18:25 UTC, SokolovYaroslav requested changes
На тесте n=239 m=5 правильный ответ 86.
Валгринд ругается оч сильно.

2020-10-17 18:25 UTC, SokolovYaroslav commented on library/commonUtils/cyclical_list.h
> +#endif //SPBU_2020_C_HOMEWORKS_1_CYCLICAL_LIST_H
Снова пустой строки нет

2020-10-18 13:44 UTC, SokolovYaroslav commented
Подтяни изменения из мастера

2020-10-18 14:20 UTC, rinatisk commented
@SokolovYaroslav  усё

2020-10-18 14:36 UTC, merged