144. Искандяров. 4.1
rinatisk/spbu_2020_c_homeworks-1 pull request #15
Opened 2020-10-14 06:56 UTC by rinatisk

2020-10-14 10:54 UTC, SpirinEgor requested changes
А у тебя работает только с односимвольными числами? Вроде несложно расширить и на просто натуральные (да и на целые тоже)

2020-10-14 10:54 UTC, SpirinEgor commented on CMakeLists.txt
> +        library/commonUtils/stack.c)
Перенеси закрывающую скобку на следующую строчку. Ещё можно прижать её к краю. Будет аккуратнее смотреться.

2020-10-14 10:54 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +const int MAX_SIZE = 100;
Правда, что эта константа нужна?
Самое простое -- считывать строку по символьно, пока не дойдёшь до конца ввода (или конца строки).
В этот момент можно сразу и парсить.

2020-10-14 10:54 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +        value += (string[position] - 48);
48 не очень понятно.
Надо либо как-то константой назвать, либо каждый раз из 0 кастовать

2020-10-14 10:54 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +        return firstOperand / secondOperand;
Давай тут сделаем отступ, чтобы не сливалось

2020-10-14 10:54 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +        return firstOperand / secondOperand;
Конечно, не обрабатываются ошибки, например, деление на 0.
Если хочешь -- можешь добавить, обычно таскают ещё указатель на переменую error. Туда кладут код ошибки, по которому потом можно понять, всё ли в порядке.

2020-10-14 10:54 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +        if (string[position] >= '*' && string[position] <= '/') {
Можно по аналогии сделать функцию isOperator

2020-10-14 10:54 UTC, SpirinEgor commented on library/commonUtils/stack.c
> +    stack->top = NULL;
А size инициализировать?

2020-10-14 13:15 UTC, rinatisk commented on Homeworks_4/4_1sol.c
> +const int MAX_SIZE = 100;
а сколько памяти тогда выделять строке? @SpirinEgor

2020-10-15 18:40 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +const int MAX_SIZE = 100;
В чате обсудили как поступить в этом случае

2020-10-15 19:28 UTC, rinatisk commented
@SpirinEgor для строк меньше 16 байт работает нормально, а если выделяется 16, то перестает работать, ровно в момент выделения перестает считывать, я не понимаю почему

2020-10-16 18:29 UTC, rinatisk commented
@SpirinEgor

2020-10-16 19:49 UTC, rinatisk commented
@SpirinEgor

2020-10-17 18:35 UTC, SpirinEgor requested changes
Не могу запустить у себя, так ты используешь malloc.h в numeric library. Исправь на stdlib.h

2020-10-17 18:35 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +            *error = -1;
Нет return для этой ветки

2020-10-17 18:35 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +            *error = -1;
Ну и для default тоже не хватает, там надо тоже ошибку отметить, неизвестная операция

2020-10-18 07:48 UTC, rinatisk commented on Homeworks_4/4_1sol.c
> +            *error = -1;
@SpirinEgor этот case запускается, только если найден оператор, поэтому я добавил проверку на неизвестную операцию в функцию подсчета

2020-10-18 18:32 UTC, rinatisk commented
@SpirinEgor

2020-10-21 11:49 UTC, SpirinEgor commented
Не надо оставлять комментарии с нашими логинами :)
Достаточно заново review запросить

2020-10-21 11:55 UTC, SpirinEgor requested changes

2020-10-21 11:55 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +    int firstOperand = getValue(pop(numbers));
Тут ты выкидываешь вершины из стека, но не освобождаешь память.
Поэтому память течёт

2020-10-21 12:27 UTC, rinatisk commented on Homeworks_4/4_1sol.c
> +    int firstOperand = getValue(pop(numbers));
поторопился

2020-10-23 12:38 UTC, SpirinEgor requested changes
Так там было одно ревью из-за malloc, где я недоглядел. Поэтому у тебя осталось ещё одно.

2020-10-23 12:38 UTC, SpirinEgor commented on Homeworks_4/4_1sol.c
> +            return 0;
return делаешь, а удалить computation и newNumber забываешь :(
Ты valgrind вообще не используешь?

2020-10-23 14:46 UTC, SpirinEgor reviewed
![Screenshot 2020-10-23 at 17 45 02](https://user-images.githubusercontent.com/22539802/97018193-8903d580-1557-11eb-8873-a1680a61794f.png)
![image](https://user-images.githubusercontent.com/22539802/97018329-b3ee2980-1557-11eb-8200-31d842e61c96.png)

2020-10-23 14:47 UTC, merged