144. Искандяров. 4.2
rinatisk/spbu_2020_c_homeworks-1 pull request #16
Opened 2020-10-14 18:04 UTC by rinatisk

2020-10-15 18:36 UTC, SpirinEgor requested changes
"По содержимому памяти"
Ты же в лоб считаешь

2020-10-17 18:23 UTC, SpirinEgor requested changes

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    int currentPlus = 1;
Plus?)
Term тогда уж, если хочешь слагаемое написать

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    double currentPlus = 0.5;
Аналогично про plus?

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +double getSmallDecimalNumber(int start, int end, char* number)
Что делает эта функция? Я из названия так и не понял. Судя по телу, вычисляет дробную часть, но не уверен.

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    }
А иначе что вернётся?
Какая-то странная реализация. Кажется, что такая функция должна принимать двоичную запись и возвращать 1 или -1. А у тебя ещё какой-то аргумент есть.

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    int exponent = getDecimalNumber(1, 11, binaryNumber) - SHIFT;
getExponent(...)

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    double mantissa = getSmallDecimalNumber(12, 63, binaryNumber) + 1;
getMantissa(...)

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    int exponent = getDecimalNumber(1, 11, binaryNumber) - SHIFT;
-SHIFT должен быть частью функции

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    double mantissa = getSmallDecimalNumber(12, 63, binaryNumber) + 1;
А тут +1 должен быть частью

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    return signOfMantissa;
```
return sign == -1 ? '-' : '+';
```

2020-10-17 18:23 UTC, SpirinEgor commented on Homeworks_4/4_2sol.c
> +    }
```
return binaryNumber[0] == '1' ? -1 : 1;
```

2020-10-18 18:32 UTC, rinatisk commented
@SpirinEgor

2020-10-21 12:02 UTC, SpirinEgor approved these changes

2020-10-21 12:03 UTC, merged