144, Искандяров, 4.3
rinatisk/spbu_2020_c_homeworks-1 pull request #17
Opened 2020-10-17 06:39 UTC by rinatisk

2020-10-17 06:40 UTC, rinatisk commented
@SpirinEgor

2020-10-17 18:41 UTC, SpirinEgor requested changes

2020-10-17 18:41 UTC, SpirinEgor commented on Homeworks_4/3sol.c
> +void getTotalByBinary(bool* binaryFirstNumber, bool* binarySecondNumber, bool* binarySum)
getBinarySum

2020-10-17 18:41 UTC, SpirinEgor commented on Homeworks_4/3sol.c
> +    int nextPlus = 1;
term

2020-10-17 18:41 UTC, SpirinEgor commented on Homeworks_4/3sol.c
> +    printBinaryNumber(binaryFirstNumber);
Добавил бы хоть какие-то пояснения к выводу, а то я запустил и получил 3 строчки из 0 и 1. Ничего непонятно, но интересно

2020-10-18 18:32 UTC, rinatisk commented
@SpirinEgor

2020-10-21 12:05 UTC, SpirinEgor approved these changes

2020-10-21 12:09 UTC, merged