144. Искандяров. 5.1
rinatisk/spbu_2020_c_homeworks-1 pull request #18
Opened 2020-10-28 15:06 UTC by rinatisk

2020-11-03 12:06 UTC, SokolovYaroslav requested changes
Почти с первого раза. Я там попридирался немного

2020-11-03 12:06 UTC, SokolovYaroslav commented on library/commonUtils/bst.c
> +    if (node->value == value) {
Yoda-style condition

2020-11-03 12:06 UTC, SokolovYaroslav commented on Homeworks_5/5_1sol.c
> +    printf("7 is help\n");
Иронично, что для того, чтобы знать, как напечатать help, надо видеть help

2020-11-03 12:06 UTC, SokolovYaroslav commented on Homeworks_5/5_1sol.c
> +    printf("7 is help\n");
А ещё какой-то крайне странный порядок у команд. 
Обычно выход где-то в конце. Похожие (в данном случае основные) идут вместе -- а тут exist с другими разделён принтами

2020-11-03 12:06 UTC, SokolovYaroslav commented on library/commonUtils/bst.c
> +            enum Direction currentDirection = left; // if we left child of node is maximum
Опечатка в комментарии?

2020-11-03 12:06 UTC, SokolovYaroslav commented on library/commonUtils/bst.c
> +void printNodeAndChildRecursive(BinarySearchTree* tree, BinaryTreeNode* node)
Children тогда уж

2020-11-03 16:21 UTC, rinatisk commented on Homeworks_5/5_1sol.c
> +    printf("7 is help\n");
я в main вызываю help, ещё до того как пользователь что то вводит, при запуске программы эти команды сразу выводятся

2020-11-07 10:56 UTC, SokolovYaroslav approved these changes

2020-11-07 10:56 UTC, merged