144, Искандяров, 1.2
rinatisk/spbu_2020_c_homeworks-1 pull request #2
Opened 2020-09-21 14:36 UTC by rinatisk

2020-09-22 15:23 UTC, SpirinEgor requested changes
Тот же комментарий про структуру

2020-09-22 15:23 UTC, SpirinEgor commented on 2sol.c
> +    int m, n;
Надо проинициализировать переменные

2020-09-22 15:23 UTC, SpirinEgor commented on 2sol.c
> +        x[right] = tmp;
Можно вынести в отдельную функцию, нам swap ещё много где понадобится

2020-09-22 15:23 UTC, SpirinEgor commented on 2sol.c
> +    int x[m + n];
Надо освободить

2020-09-23 15:15 UTC, rinatisk commented on 2sol.c
> +        x[right] = tmp;
Функции из библиотеки не хотят работать, max и min в том числе, undefined reference to `swap'  https://pastebin.com/V5M1wXsR  https://pastebin.com/erqbYzJ3    https://pastebin.com/sp002aDW    https://pastebin.com/JFUP2Xqf

2020-09-24 15:37 UTC, SpirinEgor approved these changes

2020-09-24 15:37 UTC, SpirinEgor commented on CMakeLists.txt
> +project(spbu_2020_c_homeworks-1 C)
Зачем имя проекта менять?

2020-09-24 15:40 UTC, merged