144, Искандяров, 1.3
rinatisk/spbu_2020_c_homeworks-1 pull request #3
Opened 2020-09-21 14:43 UTC by rinatisk

2020-09-22 15:25 UTC, SpirinEgor requested changes

2020-09-22 15:25 UTC, SpirinEgor commented on 3sol.c
> +    char s1[20];
Откуда 20 взялось?
Надо либо в константу выносить, либо динамическую память использовать

2020-09-22 15:25 UTC, SpirinEgor commented on 3sol.c
> +    char s1[20];
Лучше второе

2020-09-22 15:25 UTC, SpirinEgor commented on 3sol.c
> +    int s = 0, c = 0, p = 0;
Этим переменным можно дать какие-то осмысленные имена. А то по ним непонятно, за что они отвечают.

2020-09-24 07:08 UTC, rinatisk commented on 3sol.c
> +    int s = 0, c = 0, p = 0;
@SpirinEgor у меня проблема с автопроверкой стайл гайда, в каждой задаче ругается на первую строчку первый символ :1:1 
![image](https://user-images.githubusercontent.com/70975579/94111603-f0d9da00-fe4c-11ea-84c0-71015a89872e.png)
![image](https://user-images.githubusercontent.com/70975579/94111629-f9321500-fe4c-11ea-8cea-8e9547824bd5.png)
![image](https://user-images.githubusercontent.com/70975579/94111642-fd5e3280-fe4c-11ea-9f44-0ad48947fa19.png)
причем в 3 задаче после этого запушил коммит, в котором сделал изменения даже не в этой строке и проверка прошла нормально. Я так и не понял в чем причина

2020-09-24 15:25 UTC, SpirinEgor approved these changes

2020-09-24 15:25 UTC, merged