144, Искандяров, 1.4
rinatisk/spbu_2020_c_homeworks-1 pull request #4
Opened 2020-09-21 14:48 UTC by rinatisk

2020-09-22 15:41 UTC, SpirinEgor requested changes

2020-09-22 15:41 UTC, SpirinEgor commented on 4sol.c
> +    int n;
Инициализация

2020-09-22 15:41 UTC, SpirinEgor commented on 4sol.c
> +    }
Для этого есть memset

2020-09-24 14:16 UTC, SpirinEgor requested changes

2020-09-24 14:16 UTC, SpirinEgor commented on Homeworks_1/4sol.c
> +    scanf("%d", &n);
Нет приглашения к вводу

2020-09-24 14:16 UTC, SpirinEgor commented on Homeworks_1/4sol.c
> +    for (int i = 2; i < n; ++i) {
И перед циклом какой-нибудь вывод, что вот список чисел

2020-09-30 18:20 UTC, rinatisk commented
@SpirinEgor

2020-09-30 19:17 UTC, SpirinEgor approved these changes

2020-09-30 19:30 UTC, merged