144, Искандяров, 1.5
rinatisk/spbu_2020_c_homeworks-1 pull request #5
Opened 2020-09-21 14:52 UTC by rinatisk

2020-09-22 15:45 UTC, SpirinEgor requested changes

2020-09-22 15:45 UTC, SpirinEgor commented on 5sol.c
> +    int s[100000];
Опять магическое число

2020-09-22 15:45 UTC, SpirinEgor commented on 5sol.c
> +    int size, max = 0;
Инициализация

2020-09-22 15:45 UTC, SpirinEgor commented on 5sol.c
> +    int s[100000];
И можно без вспомогательного массива

2020-09-24 14:19 UTC, SpirinEgor requested changes

2020-09-24 14:19 UTC, SpirinEgor commented on Homeworks_1/5sol.c
> +int const SizeValues = 10000;
А если я захочу число больше вести, то всё сломается?
Делать такие предположения о входе не есть хорошо

2020-09-24 14:19 UTC, SpirinEgor commented on Homeworks_1/5sol.c
> +        s[x[i]]++;
Инкрементировать булевский массив, сильно...

2020-09-30 18:22 UTC, rinatisk commented
@SpirinEgor

2020-09-30 19:34 UTC, SpirinEgor approved these changes

2020-09-30 19:40 UTC, merged