144, Искандяров, 2.1
rinatisk/spbu_2020_c_homeworks-1 pull request #6
Opened 2020-09-27 08:51 UTC by rinatisk

2020-09-27 09:35 UTC, nbirillo requested changes

2020-09-27 09:35 UTC, nbirillo commented on Homeworks_2/1sol.c
> +void decompositionRecursion(int* a, int remainTerms, int maxTerm, int numberTerm)
Давай называть функции с глагола, если они что-то ДЕЛАЮТ - отдают (get), считают (count) и тд
То есть decompose number например

2020-09-27 09:35 UTC, nbirillo commented on Homeworks_2/1sol.c
> +        int j;
Переменные надо инициализировать сразу, а конкретно тут ее можно объявить внутри цикла. И почему ты выбрал `j`, чем `i` плоха?

2020-09-27 09:35 UTC, nbirillo commented on Homeworks_2/1sol.c
> +        for (j = 0; j < numberTerm - 1; j++) {
Почитай разницу про `j+`+ и `++j `например [тут](https://medium.com/better-programming/stop-using-i-in-your-loops-1f906520d548). Здесь будет эффективнее `++j`

2020-09-27 09:35 UTC, nbirillo commented on Homeworks_2/1sol.c
> +    return;
Зачем нужен `return`, если у тебя `void`?

2020-09-28 08:09 UTC, nbirillo commented
Ты обновил и значит, что можно смотреть или еще нет? Отмечай, пожалуйста `Resolve conversation`, когда их сделал + оставляй коммент с моим упоминаем, когда все поправишь или делай ререквест на ревью. Это касается всех PR

2020-09-28 09:48 UTC, nbirillo requested changes
Одно небольшое замечание и можно будет мержить

2020-09-28 09:48 UTC, nbirillo commented on Homeworks_2/1sol.c
> +    scanf("%d", &originalNumber);
Нужно говорить пользователю, что ему нужно ввести

2020-09-28 18:43 UTC, rinatisk commented on Homeworks_2/1sol.c
> +    return;
@nbirillo

2020-09-30 09:01 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-30 09:01 UTC, merged