144, Искандяров, 2.3
rinatisk/spbu_2020_c_homeworks-1 pull request #7
Opened 2020-09-27 11:33 UTC by rinatisk

2020-09-28 08:15 UTC, nbirillo requested changes

2020-09-28 08:15 UTC, nbirillo commented on Homeworks_2/2_3sol.c
> +int main()
У тебя весь код в одной функции - так не пойдет, разбей его по фуцнкциям согласно логическим частям - считывание, обработка массива, печать и тд
Сразу отмечу, что функции лучше называть с глагола, типа `printArray` и тд
Если функция что-то проверяет, то тогда с is - `isEqual` и тд

2020-09-28 08:15 UTC, nbirillo commented on Homeworks_2/2_3sol.c
> +            nonZeroIndex = nonZeroIndex + 1;
Лучше сокращать, где -то возможно. Например, тут можно написать `nonZeroIndex += 1;`

2020-09-28 08:15 UTC, nbirillo commented on Homeworks_2/2_3sol.c
> +    }
Можно сделать за один проход по массиву

2020-09-30 09:03 UTC, nbirillo requested changes

2020-09-30 09:03 UTC, nbirillo commented on Homeworks_2/2_3sol.c
> +int main()
![image](https://user-images.githubusercontent.com/8993915/94665536-f2a41180-0314-11eb-8fe5-a38542d42f3a.png)

2020-09-30 11:31 UTC, rinatisk commented on Homeworks_2/2_3sol.c
> +int main()
там нестрогое неравенство было, и поэтому выходило за пределы массива. Это так?

2020-09-30 13:51 UTC, nbirillo commented on Homeworks_2/2_3sol.c
> +int main()
ага

2020-09-30 13:52 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-30 13:52 UTC, merged