144, Искандяров, 2.4
rinatisk/spbu_2020_c_homeworks-1 pull request #8
Opened 2020-09-27 15:37 UTC by rinatisk

2020-09-28 08:20 UTC, nbirillo requested changes

2020-09-28 08:20 UTC, nbirillo commented on Homeworks_2/2_4sol.c
> +int main()
Вся логика внутри `main` - разбей на функции

2020-09-28 08:20 UTC, nbirillo commented on Homeworks_2/2_4sol.c
> +    printf("write n:\n");
Наверное, лучше **write number**?

2020-09-28 08:20 UTC, nbirillo commented on Homeworks_2/2_4sol.c
> +    int numbers[10];
Нужно сразу инициализировать массив. При этом нужно использовать константы - неудобно каждый раз писать 10 при обходе например. Ну и наверное это все же `digits`

2020-09-28 08:20 UTC, nbirillo commented on Homeworks_2/2_4sol.c
> +        }
Сделай либо цикл `while`, либо добавь условия остановки в `for`. Так себе делать `for` и `break` внутри

2020-09-28 09:03 UTC, rinatisk commented on Homeworks_2/2_4sol.c
> +    int numbers[10];
memset использовал для инициализации, или нужно как то иначе? @nbirillo

2020-09-28 09:50 UTC, nbirillo commented on Homeworks_2/2_4sol.c
> +    int numbers[10];
Если ты заменишь `10` на переменную, то тебе уже надо будет выделить память динамически тут, а ниже в `memset` указать не `10`, а переменную. Ну и в конце освободить память. Все просто - не объявляй переменные без инициализации вообще)

2020-09-30 09:07 UTC, nbirillo requested changes

2020-09-30 09:07 UTC, nbirillo commented on Homeworks_2/2_4sol.c
> +    memset(digits, 0, numberOfDigits * sizeof(int));
Но у тебя все равно остался `digits` без изначальной инициализации. Либо выдели под него динамически память, либо убери `memset` и используй `int digits[numberOfDigits] = {0}`
Так сделать можно, так как `numberOfDigits` помечена как `const`

2020-09-30 09:07 UTC, nbirillo commented on Homeworks_2/2_4sol.c
> +int main()
А еще не работает на больших числах
![image](https://user-images.githubusercontent.com/8993915/94665996-8aa1fb00-0315-11eb-8e9f-de9c01d15769.png)

2020-09-30 13:55 UTC, nbirillo requested changes
Пофикси конфликты

2020-09-30 14:23 UTC, rinatisk commented
@nbirillo

2020-09-30 15:50 UTC, nbirillo approved these changes
Отлично, зачтено!

2020-09-30 15:51 UTC, merged