144, Искандяров, 2.5
rinatisk/spbu_2020_c_homeworks-1 pull request #9
Opened 2020-09-27 18:10 UTC by rinatisk

2020-09-28 08:25 UTC, nbirillo requested changes

2020-09-28 08:25 UTC, nbirillo commented on Homeworks_2/2_5sol.c
> +#include <stdio.h>
Назови файлы согласно тому, какая весрия - рекурсивная или итеративная

2020-09-28 08:25 UTC, nbirillo commented on Homeworks_2/2_5sol_2version.c
> +    }
Почему рекурсивная версия в функции, а итеративная нет?

2020-09-28 08:25 UTC, nbirillo commented on Homeworks_2/2_5sol_2version.c
> +    for (int i = 1; i < n + 1; ++i) {
Может лучше `i <= n`? проще читать

2020-09-28 08:25 UTC, nbirillo commented on Homeworks_2/2_5sol_2version.c
> +    int answer = 1;
Давай без названий типа `answer` - делай что-то более конкретное. Что именно за `answer`

2020-09-30 09:08 UTC, nbirillo requested changes
Почини конфликты (это касается всех PR) и можно будет зачесть

2020-09-30 09:27 UTC, rinatisk commented
@nbirillo 

> Почини конфликты (это касается всех PR) и можно будет зачесть

2020-09-30 13:55 UTC, nbirillo commented
Тебе не очень везет :) К моменту как я пришла смотреть эту задачу, другая была зачтена и тут опять конфликты

2020-09-30 15:52 UTC, nbirillo commented
Конфликты :))

2020-09-30 16:50 UTC, rinatisk commented
@nbirillo а это неизбежно происходит, если все задачи сдавать за раз или можно как то избежать? Нельзя же add_executable заранее прописать для файлов, которых еще нет ни в мастере ни в локальной ветке, как я понимаю

2020-09-30 16:59 UTC, nbirillo commented
Это неизбежно происходит, потому что измнения в одном файле)

2020-09-30 16:59 UTC, nbirillo approved these changes
Зачтено!

2020-09-30 17:00 UTC, merged